---
name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check tag is on main
        run: |
          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
          MAIN_COMMIT=$(git rev-parse origin/main)
          if [ "$TAG_COMMIT" != "$MAIN_COMMIT" ]; then
            echo "Tag is not on latest main commit. Exiting."
            exit 1
          fi      
      - uses: actions/setup-node@v4
      - run: npm install
      - run: xvfb-run npm test
        if: runner.os == 'Linux'
      - run: npm run vsce-latest
      - uses: actions/upload-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
          path: 'odata-vscode-latest.vsix'

  versioned-release:
    name: Create versioned release
    needs: build
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
      - name: Rename artifact
        run: mv odata-vscode-latest.vsix odata-vscode-${{ github.ref_name }}.vsix
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: odata-vscode-${{ github.ref_name }}.vsix
          name: ${{ github.ref_name }}
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
      - name: Publish to VSCode Marketplace
        run: npx vsce publish -i odata-vscode-${{ github.ref_name }}.vsix -p ${{ secrets.VSCE_TOKEN }}