---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run vsce-latest
      - uses: actions/upload-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
          path: 'odata-vscode-latest.vsix'

  release:
    name: Create latest release
    permissions:
      contents: write    
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix artifact
        uses: actions/download-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: odata-vscode-latest.vsix
          allowUpdates: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

