---
name: "release"

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: xvfb-run npm test
        if: runner.os == 'Linux'
      - run: npm run vsce-latest
      - uses: actions/upload-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
          path: 'odata-vscode-latest.vsix'

  release:
    name: Create latest release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: odata-vscode-latest.vsix
          makeLatest: true
          allowUpdates: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

  versioned-release:
    name: Create versioned release
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download vsix artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: 'odata-vscode-latest.vsix'
      - name: Rename artifact
        run: mv odata-vscode-latest.vsix odata-vscode-${{ github.ref_name }}.vsix
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: odata-vscode-${{ github.ref_name }}.vsix
          name: ${{ github.ref_name }}
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true